### ISSUE TITLE
Error on creating instance of NYTPhotoViewer

### ISSUE THREAD

**Issue by Falgantil** [JigarM/NYTPhotoViewer-Xamarin-iOS#2]
It crashes when tapping the photo.

On simulator:

> System.InvalidProgramException: Invalid IL code in NYTPhotoViewer.NYTPhoto:.ctor (): IL_002b: stloc.0

On device:

> System.ExecutionEngineException: Attempting to JIT compile method 'NYTPhotoViewer.NYTPhoto:.ctor ()' while running with --aot-only. See http://docs.xamarin.com/ios/about/limitations for more information.

**Comment by JigarM** [comment]
No repro anymore.
Please let me know if you still face same things.
